version: '3'

services:
  backend:
    build:
      context: api_python
      dockerfile: Dockerfile
    ports:
      - '8080:8080'


  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '3000:8080'
