version: '3'

services:
  gateway:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend 

  backend:
    build:
      context: api_python
      dockerfile: Dockerfile

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
